export const SANA_HODAIE_DATA = {
  nameFa: 'ثنا هدائی',
  nameEn: 'Sana Hodaie',
  jobTitleFa: 'معمار و متخصص ارشد رایانش ابری',
  jobTitleEn: 'Senior Cloud Solutions Architect',
  companyOrOrgFa: 'مهندسی زیرساخت‌های مقیاس‌پذیر ابری',
  companyOrOrgEn: 'Scalable Cloud Systems & DevOps',
  taglineFa: 'طراحی و پیاده‌سازی زیرساخت‌های ابری مطمئن، توزیع‌شده و با پایداری ۹۹.۹۹٪',
  taglineEn: 'Architecting resilient, distributed & high-performance cloud platforms',
  phone: '09333971469',
  displayPhone: '۰۹۳۳ ۳۹۷ ۱۴۶۹',
  email: 'sana.hodaie@gmail.com',
  instagram: 'sana.hodaie',
  instagramUrl: 'https://instagram.com/sana.hodaie',
  locationFa: 'تهران، ایران | دسترسی دورکاری بین‌المللی',
  locationEn: 'Tehran, Iran | Available Globally',
  aboutFa: 'بیش از ۶ سال تجربه در معماری سیستم‌های توزیع‌شده ابری، اتوماسیون CI/CD، مدیریت کلاسترهای Kubernetes و پیاده‌سازی متدولوژی‌های DevSecOps و زیرساخت به عنوان کد (IaC).',
  aboutEn: 'Over 6 years of expertise in distributed cloud architectures, Kubernetes cluster management, IaC automation, and enterprise DevSecOps.',
  specialties: [
    {
      id: 'cloud-native',
      titleFa: 'رایانش ابری بومی (Cloud-Native)',
      titleEn: 'Cloud-Native Architecture',
      category: 'Core',
      iconName: 'Cloud',
    },
    {
      id: 'k8s-docker',
      titleFa: 'کوبرنتیز و داکر (K8s & Docker)',
      titleEn: 'Kubernetes & Containerization',
      category: 'DevOps',
      iconName: 'Boxes',
    },
    {
      id: 'iac-terraform',
      titleFa: 'زیرساخت به عنوان کد (Terraform)',
      titleEn: 'Infrastructure as Code (IaC)',
      category: 'Automation',
      iconName: 'Cpu',
    },
    {
      id: 'cloud-security',
      titleFa: 'امنیت و پایداری ابری (DevSecOps)',
      titleEn: 'Cloud Security & Resiliency',
      category: 'Security',
      iconName: 'ShieldCheck',
    },
    {
      id: 'multi-cloud',
      titleFa: 'استراتژی چندابری (Multi-Cloud)',
      titleEn: 'AWS / GCP / OpenStack Multi-Cloud',
      category: 'Strategy',
      iconName: 'Layers',
    },
    {
      id: 'observability',
      titleFa: 'مانیتورینگ و مانیتورینگ بلادرنگ',
      titleEn: 'Prometheus, Grafana & ELK',
      category: 'Observability',
      iconName: 'Activity',
    },
  ],
  stats: [
    { labelFa: 'نرخ پایداری سیستم', labelEn: 'SLA Uptime', value: '۹۹.۹۹٪' },
    { labelFa: 'کاهش هزینه‌های سرور', labelEn: 'Cloud Cost Opt.', value: '۳۵٪' },
    { labelFa: 'سرویس‌های مهاجرت داده شده', labelEn: 'Microservices Migrated', value: '+۱۲۰' },
  ],
  certifications: [
    'AWS Certified Solutions Architect',
    'Certified Kubernetes Administrator (CKA)',
    'HashiCorp Certified: Terraform Associate',
  ],
};
